### ISSUE TITLE
( BUG AndroidTutorialForBeginners VERSION 5.9.4 )  The application crashes when I try to open the application 

### ISSUE THREAD

**Issue by friendsmobile** [hussien89aa/AndroidTutorialForBeginners#12]
# Project Information

* Repository:    https://github.com/hussien89aa/AndroidTutorialForBeginners
* Project Name:  Udemy - Online Courses
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://play.google.com/store/apps/details?id=com.udemy.android

# Expected behavior

When I try to open the application, the application should open and all its options should be displayed.

# Actual behavior

 The application crashes when I try to open the application 

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.udemy.android)the application
*  open the Application 
* Note the Error
* Browser/App version:  5.9.4
* Operating system: 6.0

#### Recording Of The Bug

![20190713_152755](https://user-images.githubusercontent.com/51118734/61170482-8cb84800-a51e-11e9-9588-388a74722783.gif)

#### Logcat

<pre><code>E/AndroidRuntime(19861): FATAL EXCEPTION: main

E/AndroidRuntime(19861): Process: com.udemy.android, PID: 19861

E/AndroidRuntime(19861): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.udemy.android-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"

E/AndroidRuntime(19861): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)

E/AndroidRuntime(19861): 	at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime(19861): 	at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SourceFile:219)

E/AndroidRuntime(19861): 	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:236)

E/AndroidRuntime(19861): 	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:215)

E/AndroidRuntime(19861): 	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:208)

E/AndroidRuntime(19861): 	at com.udemy.android.dao.DBHelper.<init>(SourceFile:31)

E/AndroidRuntime(19861): 	at com.udemy.android.dao.DBHelper.getInstance(SourceFile:48)

E/AndroidRuntime(19861): 	at com.udemy.android.UdemyApplication.c(SourceFile:167)

E/AndroidRuntime(19861): 	at com.udemy.android.UdemyApplication.onCreate(SourceFile:106)

E/AndroidRuntime(19861): 	at com.udemy.android.CombinedApplication.onCreate(SourceFile:49)

E/AndroidRuntime(19861): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)

E/AndroidRuntime(19861): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4991)

E/AndroidRuntime(19861): 	at android.app.ActivityThread.access$1600(ActivityThread.java:177)

E/AndroidRuntime(19861): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)

E/AndroidRuntime(19861): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(19861): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(19861): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(19861): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(19861): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(19861): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(19861): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by XuhuiJiang** [comment]
because you lack of libsqlcipher
